language: node_js
node_js: node
before_deploy:
- openssl aes-256-cbc -K $encrypted_d06e310a6624_key -iv $encrypted_d06e310a6624_iv
  -in .travis/deploy_key.enc -out .travis/deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 .travis/deploy_key
- ssh-add .travis/deploy_key
deploy:
  provider: script
  script: npm run deploy
  skip_cleanup: true
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^(master|release-.*)$
